alurarecipes/urls.py
from django.contrib import admin
from django.urls import path, include
from recipes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipes/', include('recipes.urls'))
]

recipes/urls.py
from django.urls import path
from recipes import views

app_name = 'recipes'

urlpatterns = [
    path('', views.index, name='index'),
    path('recipe/<int:pk>', views.recipe, name='recipe'),
]

recipes/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Recipe(models.Model):
    def __str__(self) -> str:
        return self.name
    
    class Meta:
        verbose_name = 'Receita'
        verbose_name_plural = 'Receitas'

    name = models.CharField(
        max_length=50
    )
    name.verbose_name = 'Nome'

    ingredients = models.TextField(
        max_length=1000
    )
    ingredients.verbose_name = 'Ingredientes'

    prepare_mode = models.TextField(
        max_length=1000
    )
    prepare_mode.verbose_name = 'Modo de preparo'

    preparation_time = models.IntegerField()
    preparation_time.verbose_name = 'Tempo de preparo'

    portions = models.IntegerField()
    portions.verbose_name = 'Porções'

    category = models.CharField(max_length=50)
    category.verbose_name = 'Categoria'

    created_at = models.DateTimeField(default=datetime.now, blank=True, editable=False)
    created_at.verbose_name = 'Criado em'

recipes/views.py
from django.shortcuts import render, get_object_or_404

from recipes.models import Recipe

# Create your views here.
def index(request):   
    recipes = Recipe.objects.all()

    context = {
        'recipes': recipes
    } 

    return render(request, 'recipes/index.html', context)

def recipe(request, pk):
    recipe = get_object_or_404(Recipe, pk=pk)

    context = {
        'recipe': recipe
    }

    return render(request, 'recipes/recipe.html', context)

recipes/templates/partials/footer.html
{%load static %}

<!-- ##### Footer Area Start ##### -->
<footer class="footer-area">
    <div class="container h-100">
        <div class="row h-100">
            <div class="col-12 h-100 d-flex flex-wrap align-items-center justify-content-between">
                <!-- Footer Social Info -->
                <div class="footer-social-info text-right">
                    <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                </div>
                <!-- Footer Logo -->
                <div class="footer-logo">
                    <a href="{% url 'recipes:index' %}"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- ##### Footer Area Start ##### -->

recipes/templates/partials/menu.html
{% load static %} <!-- we need to load static files -->

<!-- ##### Header Area Start ##### -->
<header class="header-area">

    <!-- Top Header Area -->
    <div class="top-header-area">
        <div class="container h-100">
            <div class="row h-100 align-items-center justify-content-between">
                <!-- Breaking News -->
                <div class="col-12 col-sm-6">
                    <div class="breaking-news">
                        <div id="breakingNewsTicker" class="ticker">
                            <ul>
                                <li><a href="">Boas vindas!</a></li>
                                <li><a href="">As melhores receitas</a></li>
                                <li><a href="">Você encontra aqui!</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <!-- Top Social Info -->
                <div class="col-12 col-sm-6">
                    <div class="top-social-info text-right">
                        <a href=""><i class="fa fa-facebook" aria-hidden="true"></i></a>
                        <a href=""><i class="fa fa-twitter" aria-hidden="true"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Navbar Area -->
    <div class="delicious-main-menu">
        <div class="classy-nav-container breakpoint-off">
            <div class="container">
                <!-- Menu -->
                <nav class="classy-navbar justify-content-between" id="deliciousNav">

                    <!-- Logo -->
                    <a class="nav-brand" href="{% url 'recipes:index' %}"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>

                    <!-- Navbar Toggler -->
                    <div class="classy-navbar-toggler">
                        <span class="navbarToggler"><span></span><span></span><span></span></span>
                    </div>

                    <!-- Menu -->
                    <div class="classy-menu">

                        <!-- close btn -->
                        <div class="classycloseIcon">
                            <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                        </div>

                        <!-- Nav Start -->
                        <div class="classynav">
                            <ul>
                                <li><a href="{% url 'recipes:index' %}">Home</a></li>                                
                            </ul>

                            <!-- Formulario de busca -->
                            <div class="search-btn">
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </div>
                            <!-- Formulario de busca -->

                        </div>
                        <!-- Nav End -->
                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>
<!-- ##### Header Area End ##### -->

recipes/templates/recipes/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Título -->
    <title>Alura Receitas</title>

    <!-- Favicon -->
    <link rel="icon" href="{% static '/img/core-img/favicon.ico' %}">

    <!-- Stylesheet -->
    <link rel="stylesheet" href="{% static 'site.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

</head>

<body>
    <!-- Preloader -->
    <div id="preloader">
        <i class="circle-preloader"></i>
        <img src="{% static 'img/core-img/pizza.png' %}" alt="">
    </div>

    <!-- Search Wrapper -->
    <div class="search-wrapper">
        <!-- Close Btn -->
        <div class="close-btn"><i class="fa fa-times" aria-hidden="true"></i></div>

        <div class="container">
            <div class="row">
                <div class="col-12">
                    <form action="#" method="post">
                        <input type="search" name="search" placeholder="O que está procurando...">
                        <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {%include 'partials/menu.html' %}

    <!-- ##### Best Receipe Area Start ##### -->
    <section class="best-receipe-area">
        <div class="container">
            <div class="row">
                <!-- Single Best Receipe Area -->
                {% for recipe in recipes %}
                <div class="col-12 col-sm-6 col-lg-4">
                    <div class="single-best-receipe-area mb-30">
                        <img src="{% static 'img/bg-img/foto_receita.png'%}" alt="">
                        <div class="receipe-content">
                            <a href="{% url 'recipes:recipe' recipe.pk %}">
                                <h5>{{recipe.name}}</h5>
                            </a>
                        </div>
                    </div>
                </div>  
                {% endfor %}
                              
            </div>
        </div>
    </section>
    <!-- ##### Best Receipe Area End ##### -->

    {% include 'partials/footer.html' %}

    <!-- ##### All Javascript Files ##### -->
    <!-- jQuery-2.2.4 js -->
    <script src="{% static  'js/jquery/jquery-2.2.4.min.js' %} "></script>
    <!-- Popper js -->
    <script src="{% static  'js/bootstrap/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <!-- All Plugins js -->
    <script src="{% static 'js/plugins/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'js/active.js' %}"></script>
</body>

</html>

recipes/templates/recipes/recipe.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title -->
    <title>Alura Receitas</title>

    <!-- Favicon -->
    <link rel="icon" href="img/core-img/favicon.ico">

    <!-- Core Stylesheet -->

      <!-- Favicon -->
      <link rel="icon" href="{% static '/img/core-img/favicon.ico' %}">

      <!-- Stylesheet -->
      <link rel="stylesheet" href="{% static 'site.css' %}">
      <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

</head>

<body>
    <!-- Preloader -->
    <div id="preloader">
        <i class="circle-preloader"></i>
        <img src="{% static 'img/core-img/hamburger.png' %}" alt="">
    </div>

    <!-- Search Wrapper -->
    <div class="search-wrapper">
        <!-- Close Btn -->
        <div class="close-btn"><i class="fa fa-times" aria-hidden="true"></i></div>

        <div class="container">
            <div class="row">
                <div class="col-12">
                    <form action="#" method="post">
                        <input type="search" name="search" placeholder="O que está procurando...">
                        <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {%include 'partials/menu.html' %}
    

        <!-- Receipe Post Search -->
        <div class="receipe-post-search mb-80">
            <div class="container">
                <form action="#" method="post">
                    <div class="row">
                        <div class="col-12 col-lg-5">
                            <select name="select1" id="select1">
                                <option value="1">Comida típica brasileira</option>
                                <option value="1">Massas</option>
                                <option value="1">Veganas</option>
                            </select>
                        </div>
                        <div class="col-12 col-lg-2 text-right">
                            <button type="submit" class="btn delicious-btn">Buscar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <!-- Receipe Slider -->
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="receipe-slider owl-carousel">
                        <img src="{% static 'img/bg-img/tomate_banner.jpg' %}">
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Receipe Content Area -->
        <div class="receipe-content-area">
            <div class="container">

                <div class="row">
                    <div class="col-12 col-md-8">
                        <div class="receipe-headline my-5">
                            <span>{{recipe.created_at}}</span>
                            <h2>{{recipe.name}}</h2>
                            <div class="receipe-duration">
                                <h6>Preparo: {{ recipe.preparation_time }} minutos</h6>
                                <h6>Rendimento: {{recipe.portions}} porçoes</h6>
                                <h6>Categoria: {{recipe.category}}</h6>
                                <h6>Por: Pessoa</h6>
                            </div>
                        </div>
                    </div>

                <div class="row">
                    <div class="col-12 col-lg-8">
                        <!-- Single Preparation Step -->
                        <div class="single-preparation-step d-flex">
                            <p>
                                {{recipe.prepare_mode}}
                            </p>
                        </div>
                    </div>

                    <!-- Ingredientes -->
                    <div class="col-12 col-lg-4">
                        <div class="ingredients">
                            <h4>Ingredientees</h4>
                            <div class="ingredients">
                                <p>
                                    {{recipe.ingredients}}    
                                </p>
                            </p>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Ingredientes -->

    {% include 'partials/footer.html' %}

    <!-- ##### All Javascript Files ##### -->
    <!-- jQuery-2.2.4 js -->
    <script src="{% static  'js/jquery/jquery-2.2.4.min.js' %} "></script>
    <!-- Popper js -->
    <script src="{% static  'js/bootstrap/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <!-- All Plugins js -->
    <script src="{% static 'js/plugins/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'js/active.js' %}"></script>
</body>

</html>